version: '3.8'

## This file is meant to be used for developing on a local machine.
## Use only the main Compose file when deploying to production using:
## docker-compose -f docker-compose.yaml <command>
services:

    server:
        image: 'zanbaldwin/stack/server/development'
        build:
            target: 'development'
        volumes:
            # Use self-generated certificates during development.
            -   type: 'bind'
                source: './build/.secrets/ssl'
                target: '/etc/letsencrypt'
                read_only: true
            -   type: 'bind'
                source: './build/.secrets/ssl/ca.pem'
                target: '/etc/ssl/certs/ca-certificates.crt'
                read_only: true

    php:
        image: 'zanbaldwin/stack/php/development'
        build:
            target: 'development'
            args:
                ENABLE_XDEBUG: 'yes'
        environment:
            PHP_IDE_CONFIG: 'serverName=${PHPSTORM_SERVER_NAME:-stack}'
        extra_hosts:
            # Add an entry in /etc/hosts to point to the host machine (for XDebug).
            - 'host.docker.internal:host-gateway'

    database:
        image: 'zanbaldwin/stack/database/development'
        build:
            target: 'development'
        volumes:
            # Use a volume for data during development instead of messing with
            # system directories.
            -   type: 'volume'
                source: 'database'
                target: '/var/lib/mysql'
                read_only: false

    migrate:
        image: 'zanbaldwin/stack/migrate/development'
        build:
            target: 'development'

    queue:
        image: 'rabbitmq:3.9.11-management-alpine'
        volumes:
            # Use a volume for data during development instead of messing with
            # system directories.
            -   type: 'volume'
                source: 'queue'
                target: '/var/lib/rabbitmq'
                read_only: false
        ports:
            -   target: 15672
                published: '${QUEUE_MANAGEMENT_PORT:-15672}'
                protocol: 'tcp'
                mode: 'host'

    workers:
        image: 'zanbaldwin/stack/php/development'
        build:
            target: 'development'
            args:
                ENABLE_XDEBUG: 'yes'
        environment:
            PHP_IDE_CONFIG: 'serverName=${PHPSTORM_SERVER_NAME:-stack}'
        extra_hosts:
            # Add an entry in /etc/hosts to point to the host machine (for XDebug).
            - 'host.docker.internal:host-gateway'
        command: ['php', 'bin/console', 'messenger:consume']

    redis:
        image: 'zanbaldwin/stack/redis/development'
        build:
            target: 'development'
        volumes:
            # Use a volume for data during development instead of messing with
            # system directories.
            -   type: 'volume'
                source: 'redis'
                target: '/data'
                read_only: false

volumes:
    database:
        driver: 'local'
    queue:
        driver: 'local'
    redis:
        driver: 'local'
