version: '3.8'

x-logging:
  &default-logging
    driver: 'json-file'
    options:
        max-size: '5m'
        max-file: '1'

services:

    server:
        image: 'zanbaldwin/stack/server:${VERSION:-latest}'
        build:
            context: './build/docker/server'
            args:
                NGINX_VERSION: '1.21.4'
                DOMAIN: '${DOMAIN:-localhost}'
        restart: 'unless-stopped'
        depends_on:
            - 'php'
        ports:
            -   target: 80
                published: '${WEB_PORT:-80}'
                protocol: 'tcp'
                mode: 'host'
            -   target: 443
                published: '${SSL_PORT:-443}'
                protocol: 'tcp'
                mode: 'host'
        volumes:
            -   type: 'bind'
                source: './public'
                target: '/srv/public'
                read_only: true
            -   type: 'bind'
                source: '/etc/letsencrypt'
                target: '/etc/letsencrypt'
                read_only: true
        logging: *default-logging

    php:
        image: 'zanbaldwin/stack/php:${VERSION:-latest}'
        build:
            context: './build/docker/php'
            args:
                PHP_VERSION: '8.1'
                GOLANG_VERSION: '1.16.5'
                ROADRUNNER_VERSION: '2.3.0'
        restart: 'unless-stopped'
        depends_on:
            -   'database'
            -   'redis'
        volumes:
            -   type: 'bind'
                source: './'
                target: '/srv'
                read_only: false
        logging: *default-logging

    database:
        image: 'zanbaldwin/stack/database:${VERSION:-latest}'
        build:
            context: './build/docker/database'
            args:
                MYSQL_VERSION: '8.0.27'
        restart: 'unless-stopped'
        environment:
            MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/dbpass'
            MYSQL_DATABASE: 'main'
        volumes:
            -   type: 'bind'
                source: '/opt/mysql'
                target: '/var/lib/mysql'
                read_only: false
        secrets:
            -   'dbpass'
        logging: *default-logging

    migrate:
        image: 'zanbaldwin/stack/migrate:${VERSION:-latest}'
        build:
            context: './build/docker/migrate'
            args: {}
        depends_on:
            -   'database'
        volumes:
            -   type: bind
                source: './migrations'
                target: '/migrations'
                read_only: true
        env_file:
            -   './.env'
        logging: *default-logging

    redis:
        image: 'zanbaldwin/stack/redis:${VERSION:-latest}'
        build:
            context: './build/docker/redis'
            args:
                REDIS_VERSION: '6.2.6'
        restart: 'unless-stopped'
        volumes:
            -   type: 'bind'
                source: '/opt/redis'
                target: '/data'
                read_only: false
        logging: *default-logging

secrets:
    dbpass:
        file: './build/.secrets/dbpass'
